FROM python:3.9-slim

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean

WORKDIR /app

# Копируем зависимости
COPY requirements.cv.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.cv.txt

# Копируем файлы проекта
COPY . .

# Открываем порт для API
EXPOSE 8000

# Запуск скрипта обработки и сервера API
CMD ["python", "video_recognition/stream_recognition.py"]
