version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telegram_bot
    volumes:
      - shared_volume:/shared
    networks:
      - botnet

  cv_container:
    build:
      context: .
      dockerfile: Dockerfile.cv
    container_name: cv_container
    ports:
      - "8000:8000"
    volumes:
      - shared_volume:/shared
    networks:
      - botnet

volumes:
  shared_volume:

networks:
  botnet:
    driver: bridge
