FROM python:3.9-slim

# Установка зависимостей
RUN apt-get update && apt-get install -y \
    libglib2.0-0 libsm6 libxrender-dev libxext6 \
    && apt-get clean

WORKDIR /app

# Копируем зависимости
COPY requirements.bot.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.bot.txt

# Копируем файлы проекта
COPY . .

# Запуск бота
CMD ["python", "aiogram/start_bot.py"]
